const projectsArr = [
    {   name: 'Tetris', 
        description: 'blah', 
        image: 'https://i.imgur.com/eVAblrC.png',
        site: 'https://christinew2-tetris.netlify.app/', 
        github: 'https://github.com/christinew2/christinew2-tetris',
    },
    {   name: 'HomeCooked', 
        description: 'blah2', 
        image: 'https://i.imgur.com/eVAblrC.png',
        site: 'https://christinew2-homecooked.herokuapp.com/', 
        github: 'https://github.com/christinew2/homecooked-unit2',
    },
    {   name: 'PartyFowl', 
        description: 'blah3', 
        image: 'https://i.imgur.com/eVAblrC.png',
        site: 'https://partyfowl.herokuapp.com/', 
        github: 'https://github.com/christinew2/partyfowl',
    },
    {   name: 'yooDoo', 
        description: 'blah4', 
        image: 'https://i.imgur.com/eVAblrC.png',
        site: 'https://christinew2-yoodoo.herokuapp.com/', 
        github: 'https://github.com/christinew2/yooDoo',
    },
    {   name: 'portfolio', 
        description: 'blah5', 
        image: 'GitHub-Mark-64px.png',
        site: 'site5', 
        github: 'https://github.com/christinew2/portfolio',
    },
]

export default projectsArr